"""Üniversite bölümleri — kapalı liste.

Kullanıcılar bölümü serbest metin olarak yazamaz; yalnızca bu listeden seçer
(profil alanları tutarlı kalsın, ileride "aynı bölümden ev arkadaşı" gibi
eşleştirmeler mümkün olsun diye). Liste YÖK lisans programları temel alınarak
alan gruplarına ayrıldı; yeni program eklemek için ilgili gruba bir satır.
"""

DEPARTMENT_GROUPS: dict[str, list[str]] = {
    "Mühendislik": [
        "Bilgisayar Mühendisliği",
        "Yazılım Mühendisliği",
        "Yapay Zeka ve Veri Mühendisliği",
        "Elektrik-Elektronik Mühendisliği",
        "Elektrik Mühendisliği",
        "Elektronik ve Haberleşme Mühendisliği",
        "Makine Mühendisliği",
        "Mekatronik Mühendisliği",
        "İnşaat Mühendisliği",
        "Endüstri Mühendisliği",
        "Endüstri ve Sistem Mühendisliği",
        "Kimya Mühendisliği",
        "Gıda Mühendisliği",
        "Çevre Mühendisliği",
        "Biyomedikal Mühendisliği",
        "Biyomühendislik",
        "Genetik ve Biyomühendislik",
        "Malzeme Bilimi ve Mühendisliği",
        "Metalurji ve Malzeme Mühendisliği",
        "Havacılık ve Uzay Mühendisliği",
        "Uçak Mühendisliği",
        "Uzay Mühendisliği",
        "Gemi İnşaatı ve Gemi Makineleri Mühendisliği",
        "Deniz Ulaştırma İşletme Mühendisliği",
        "Harita Mühendisliği",
        "Geomatik Mühendisliği",
        "Jeoloji Mühendisliği",
        "Jeofizik Mühendisliği",
        "Maden Mühendisliği",
        "Petrol ve Doğalgaz Mühendisliği",
        "Enerji Sistemleri Mühendisliği",
        "Nükleer Enerji Mühendisliği",
        "Tekstil Mühendisliği",
        "Orman Endüstri Mühendisliği",
        "Ziraat Mühendisliği",
        "Tarımsal Biyoteknoloji",
        "Otomotiv Mühendisliği",
        "İmalat Mühendisliği",
        "Kontrol ve Otomasyon Mühendisliği",
        "Bilişim Sistemleri Mühendisliği",
        "Yönetim Bilişim Sistemleri",
        "Endüstriyel Tasarım Mühendisliği",
    ],
    "Mimarlık, Tasarım ve Planlama": [
        "Mimarlık",
        "İç Mimarlık",
        "İç Mimarlık ve Çevre Tasarımı",
        "Peyzaj Mimarlığı",
        "Şehir ve Bölge Planlama",
        "Endüstriyel Tasarım",
        "Endüstri Ürünleri Tasarımı",
        "Grafik Tasarım",
        "Görsel İletişim Tasarımı",
        "Moda Tasarımı",
        "Moda ve Tekstil Tasarımı",
        "Tekstil ve Moda Tasarımı",
        "Oyun Tasarımı",
        "Animasyon",
        "Dijital Oyun Tasarımı",
    ],
    "Sağlık Bilimleri": [
        "Tıp",
        "Diş Hekimliği",
        "Eczacılık",
        "Veterinerlik",
        "Hemşirelik",
        "Ebelik",
        "Beslenme ve Diyetetik",
        "Fizyoterapi ve Rehabilitasyon",
        "Odyoloji",
        "Dil ve Konuşma Terapisi",
        "Ergoterapi",
        "Sağlık Yönetimi",
        "Çocuk Gelişimi",
        "Sosyal Hizmet",
        "Perfüzyon",
        "Ortez ve Protez",
        "Gerontoloji",
        "İş Sağlığı ve Güvenliği",
        "Acil Yardım ve Afet Yönetimi",
        "Tıbbi Laboratuvar Teknikleri",
        "Sağlık Bilimleri (diğer)",
    ],
    "Fen Bilimleri": [
        "Matematik",
        "Uygulamalı Matematik",
        "Matematik Mühendisliği",
        "İstatistik",
        "Fizik",
        "Fizik Mühendisliği",
        "Kimya",
        "Biyoloji",
        "Moleküler Biyoloji ve Genetik",
        "Biyoteknoloji",
        "Astronomi ve Uzay Bilimleri",
        "Yer Bilimleri",
        "Su Ürünleri",
        "Aktüerya Bilimleri",
        "Veri Bilimi ve Analitiği",
    ],
    "Sosyal ve Beşeri Bilimler": [
        "Psikoloji",
        "Sosyoloji",
        "Felsefe",
        "Tarih",
        "Sanat Tarihi",
        "Arkeoloji",
        "Antropoloji",
        "Coğrafya",
        "Türk Dili ve Edebiyatı",
        "Dilbilim",
        "Halkla İlişkiler ve Tanıtım",
        "Gazetecilik",
        "Radyo, Televizyon ve Sinema",
        "Yeni Medya ve İletişim",
        "İletişim Bilimleri",
        "Reklamcılık",
        "Uluslararası İlişkiler",
        "Siyaset Bilimi",
        "Siyaset Bilimi ve Kamu Yönetimi",
        "Kamu Yönetimi",
        "Felsefe Grubu Öğretmenliği",
        "Bilgi ve Belge Yönetimi",
        "Din Kültürü ve Ahlak Bilgisi",
        "İlahiyat",
        "Mütercim-Tercümanlık",
        "Çeviribilim",
    ],
    "İktisadi ve İdari Bilimler": [
        "İşletme",
        "İktisat",
        "Ekonomi",
        "Ekonomi ve Finans",
        "Maliye",
        "Muhasebe ve Finans Yönetimi",
        "Bankacılık ve Finans",
        "Sigortacılık ve Risk Yönetimi",
        "Uluslararası Ticaret ve Lojistik",
        "Lojistik Yönetimi",
        "İnsan Kaynakları Yönetimi",
        "Pazarlama",
        "Girişimcilik",
        "Turizm İşletmeciliği",
        "Gastronomi ve Mutfak Sanatları",
        "Otel Yöneticiliği",
        "Havacılık Yönetimi",
        "Sağlık Kurumları İşletmeciliği",
        "Emlak ve Emlak Yönetimi",
        "Çalışma Ekonomisi ve Endüstri İlişkileri",
        "Ekonometri",
    ],
    "Hukuk ve Güvenlik": [
        "Hukuk",
        "Adalet",
        "Güvenlik Bilimleri",
        "Uluslararası Hukuk",
    ],
    "Eğitim": [
        "Sınıf Öğretmenliği",
        "Okul Öncesi Öğretmenliği",
        "Matematik Öğretmenliği",
        "Fen Bilgisi Öğretmenliği",
        "Türkçe Öğretmenliği",
        "Türk Dili ve Edebiyatı Öğretmenliği",
        "İngilizce Öğretmenliği",
        "Almanca Öğretmenliği",
        "Fransızca Öğretmenliği",
        "Tarih Öğretmenliği",
        "Coğrafya Öğretmenliği",
        "Fizik Öğretmenliği",
        "Kimya Öğretmenliği",
        "Biyoloji Öğretmenliği",
        "Rehberlik ve Psikolojik Danışmanlık",
        "Özel Eğitim Öğretmenliği",
        "Bilgisayar ve Öğretim Teknolojileri Öğretmenliği",
        "Beden Eğitimi ve Spor Öğretmenliği",
        "Müzik Öğretmenliği",
        "Resim-İş Öğretmenliği",
        "Sosyal Bilgiler Öğretmenliği",
        "İlköğretim Matematik Öğretmenliği",
    ],
    "Dil ve Edebiyat": [
        "İngiliz Dili ve Edebiyatı",
        "Amerikan Kültürü ve Edebiyatı",
        "Alman Dili ve Edebiyatı",
        "Fransız Dili ve Edebiyatı",
        "İspanyol Dili ve Edebiyatı",
        "İtalyan Dili ve Edebiyatı",
        "Rus Dili ve Edebiyatı",
        "Arap Dili ve Edebiyatı",
        "Fars Dili ve Edebiyatı",
        "Japon Dili ve Edebiyatı",
        "Çin Dili ve Edebiyatı",
        "Kore Dili ve Edebiyatı",
        "Karşılaştırmalı Edebiyat",
    ],
    "Güzel Sanatlar ve Spor": [
        "Resim",
        "Heykel",
        "Seramik ve Cam",
        "Geleneksel Türk Sanatları",
        "Fotoğraf",
        "Sinema ve Televizyon",
        "Tiyatro",
        "Oyunculuk",
        "Sahne Sanatları",
        "Müzik",
        "Müzikoloji",
        "Ses ve Müzik Teknolojileri",
        "Konservatuvar",
        "Antrenörlük Eğitimi",
        "Spor Yöneticiliği",
        "Rekreasyon",
        "Egzersiz ve Spor Bilimleri",
    ],
    "Denizcilik, Havacılık ve Ulaştırma": [
        "Pilotaj",
        "Hava Trafik Kontrol",
        "Uçak Bakım ve Onarım",
        "Kabin Hizmetleri",
        "Denizcilik İşletmeleri Yönetimi",
        "Gemi Makineleri İşletme Mühendisliği",
        "Ulaştırma ve Lojistik",
    ],
    "Diğer": [
        "Hazırlık / Henüz Bölüm Seçmedim",
        "Yüksek Lisans / Doktora",
        "Listede Yok",
    ],
}

# Doğrulama için düz küme (grup fark etmeksizin)
ALL_DEPARTMENTS: set[str] = {
    name for names in DEPARTMENT_GROUPS.values() for name in names
}


def is_valid(department: str | None) -> bool:
    """Boş bırakmak serbest; doluysa listede olmalı."""
    return department is None or department in ALL_DEPARTMENTS
